roles:
  defaultMemberRole: 782242269834641409
  moderationRoles:
    - 782242591986155530
    - 782242378668310539

channels:
  botLog: 782242998767058944

presenceUpdate:
  presenceUpdateFrequency: 5000
  statuses:
    - "Instagram: aybuse.uslu"
    - "Youtube: Aybusee"
    - "Twitter: aybuseuslu"

greeting:
  greetingDirectMessage: "**Aybuse**'nin Sunucusuna HoÅŸgeldin :tada:\n:small_orange_diamond: Hemen ***Kurallar*** kanalÄ±na bakmayÄ± unutma,\n:small_orange_diamond: EÄŸer bir sorun olursa moderatÃ¶rlere bildirebilirsin.\n\n**Aybuse'yi sosyal medyadan takip etmek iÃ§in**\n:small_blue_diamond: Ä°nstagram: *https://www.instagram.com/aybuse.uslu/*\n:small_blue_diamond: YouTube: *https://www.youtube.com/channel/UCercN6vdTVn07CadGL1Nesw*\n:small_blue_diamond: Twitter: *https://twitter.com/aybuseuslu*"
  greetingChannel: 782242976419282986
  greetingMessages:
    - UyandÄ±ÄŸÄ±nda <#386992275332399108> e 'GÃ¼naydÄ±n' demeyi unutma saat kaÃ§ta uyandÄ±ÄŸÄ±nÄ± merak ediyoruz.
    - GÃ¼nÃ¼n her saatinde sohbet odalarÄ±nda boÅŸ yapÄ±lÄ±yor, istersen bi' dene.
    - "YayÄ±ndan bol bol clip alÄ±p #clipler odasÄ±na atmayÄ± unutma, sen de turuncu bir 'clipper' olabilirsin!"
    - GacÄ±ysan 'huri' rolÃ¼nÃ¼ denemelisin!
    - Buyur kolonya <:golonya:691917008341565452> aman diyim bize corona bulaÅŸtÄ±rma.
    - Birlikte Ã§Ä±plak noel babalarÄ± popÃ¼ler yapalÄ±m mÄ±?
    - O da ne, uÃ§an bir Ã‡oti mi?
    - Aybusenin buffÄ±nÄ± gÃ¶rdÃ¼n mÃ¼?
    - KÃ¼tahya'nÄ±n kireÃ§li suyundan bi' bardak ister misin?

urlRestriction:
  warningMessage: "bu metin kanalÄ±nda link paylaÅŸÄ±mÄ± yasaktÄ±r."
  restrictedChannels:
    - 782242136731942945

ticket:
  messageId: 782600181534687275
  reaction: ğŸŸï¸
  roleId: 782242338167849011