#Bot's own user id for ignoring it in some cases.
botUserId: 691737456575250432
baseImagePath: images

#Role groups
roles:
  subRole: 388714942242488320
  serverBoosterRole: 651507582988451841
  defaultMemberRole: 440529266061344769
  muteRole: 491263963359870976
  gradedMembersRole: 848000629577875478
  serverFirstMemberRole: 848000771475374090
  serverSecondMemberRole: 848000821353512960
  serverThirdMemberRole: 848000842837917728
  moderationRoles:
    - 387310485646606349
    - 477147540580728853
    - 782244241254252585
    - 693086824297398332
    - 672508565902065694
    - 388726329492766722

channels:
  botLog: 442441995265376287
  aybus: 608015865320964119
  sohbet: 386992275332399108
  afk: 387628516797054986

presenceUpdate:
  presenceUpdateFrequency: 5000
  statuses:
    - "Instagram: aybuse.uslu"
    - "Youtube: Aybuse"
    - "Twitter: aybuseuslu"
    - "aybushbot.com"

greeting:
  greetingDirectMessage: "**Aybuse**'nin Sunucusuna HoÅŸgeldin :tada:\n:small_orange_diamond: Hemen ***Kurallar*** kanalÄ±na bakmayÄ± unutma,\n:small_orange_diamond: EÄŸer bir sorun olursa moderatÃ¶rlere bildirebilirsin.\n\n**Aybuse'yi sosyal medyadan takip etmek iÃ§in**\n:small_blue_diamond: Ä°nstagram: *https://www.instagram.com/aybuse.uslu/*\n:small_blue_diamond: YouTube: *https://www.youtube.com/channel/UCercN6vdTVn07CadGL1Nesw*\n:small_blue_diamond: Twitter: *https://twitter.com/aybuseuslu*"
  greetingChannel: 454039614802362369
  greetingMessages:
    - UyandÄ±ÄŸÄ±nda <#386992275332399108> e 'GÃ¼naydÄ±n' demeyi unutma saat kaÃ§ta uyandÄ±ÄŸÄ±nÄ± merak ediyoruz.
    - GÃ¼nÃ¼n her saatinde sohbet odalarÄ±nda boÅŸ yapÄ±lÄ±yor, istersen bi' dene.
    - "YayÄ±ndan bol bol clip alÄ±p <#595912902074957861> odasÄ±na atmayÄ± unutma, sen de turuncu bir 'clipper' olabilirsin!"
    - GacÄ±ysan 'huri' rolÃ¼nÃ¼ denemelisin!
    - Buyur kolonya <:golonya:691917008341565452> aman diyim bize corona bulaÅŸtÄ±rma.
    - Birlikte Ã§Ä±plak noel babalarÄ± popÃ¼ler yapalÄ±m mÄ±?
    - O da ne, uÃ§an bir Ã‡oti mi?
    - Aybusenin buffÄ±nÄ± gÃ¶rdÃ¼n mÃ¼?
    - KÃ¼tahya'nÄ±n kireÃ§li suyundan bi' bardak ister misin?

urlRestriction:
  warningMessage: "bu metin kanalÄ±nda link paylaÅŸÄ±mÄ± yasaktÄ±r."
  restrictedChannels:
    - 386992275332399108

ticket:
  messageId: 714539807593988106
  reaction: ğŸŸï¸
  roleId: 714231810758017024

#Spam protection configurations
antiSpam:
  ignoredChannels:
    - 823686505737617408
    - 823688889989333052
    - 469043458321940491
  mute:
    threshold: 4
    maxDuplicates: 8
    message: "Spam yaptÄ±ÄŸÄ±n iÃ§in %v dakika susturuldun. Bu davranÄ±ÅŸÄ±na devam edersen sunucudan atÄ±labilirsin."
    channelMessage: "<@%v> spam sebebiyle %v dakika susturuldu."
    duration: 600000
  maxInterval: 2000
  maxDuplicatesInterval: 300000

loveMeter:
  texts:
    - Sizin aÅŸkla alakanÄ±z yok hatta birbirinizden nefre ediyorsunuz.
    - Bence hiÃ§ zorlamayÄ±n.
    - Birbirinizin tipi deÄŸilsiniz.
    - Birbirinizi tanÄ±rsanÄ±z belki.
    - Az da olsa birbirinize karÅŸÄ± biÅŸeyler hissediyorsunuz.
    - Bence uÄŸraÅŸÄ±rsanÄ±z bu iÅŸ olur.
    - Siz kesin birbirinizden hoÅŸlanÄ±yorsunuz.
    - Galiba birbirinizi seviyorsunuz.
    - Birbirinizi seviyorsunuz, bu aÅŸk olmazsa dÃ¼nya size kÃ¼ser.
    - BUNA AÅK DENÄ°R!
    - SÄ°Z BÄ°RBÄ°RÄ°NÄ°ZE AÅIKSINIZ <3.

rockPaperScissors:
  defaultAvatar: discord.jpg
  hostWins: backgroundHostWins.png
  awayWins: backgroundAwayWins.png
  draw: backgroundDraw.png

levelSystem:
  background: rank_bg.png
  ignoredTextChannels:
    - 608015865320964119
    - 469043458321940491
    - 823686505737617408
    - 823688889989333052
    - 690696295148683304
  ignoredVoiceChannels:
    - 387628516797054986